### ISSUE TITLE
Убрать из списков @dotnetby

### ISSUE THREAD

**Issue by Keroosha** [fsharplang-ru/grinder#19]
На каждый бан в логах одно и тоже сообщение:

```
Error on baning userId $USERID$ in chat "@dotnetby" until 09/15/2024 18:38:38. Failed to ban $USERID$ in chat @dotnetby. Description: Bad Request: chat not found
```

Сам чат уже миллиард лет как не существует

![image](https://github.com/fsharplang-ru/grinder/assets/3408281/ae727c9d-483b-4e81-8d2e-76c076e202a0)

**Comment by Szer** [comment]
Говорят, чат ушёл в приват режим, не достучаться. Ну и RIP.
Убрал из конфига
